define(function() {
  var filterResult = {
    "dept":[
      {
          "deptId":"wbalone100000018da8",
          "deptName":"测试部04",
          "psnNum":1,
          "psndocList":null,
          "principal":null,
          "principalName":null,
          "principalAvatar":null
      },
      {
          "deptId":"wbalone100000018d9g",
          "deptName":"测试部03",
          "psnNum":1,
          "psndocList":null,
          "principal":null,
          "principalName":null,
          "principalAvatar":null
      },
      {
          "deptId":"wbalone100000018d9c",
          "deptName":"测试部02",
          "psnNum":1,
          "psndocList":null,
          "principal":null,
          "principalName":null,
          "principalAvatar":null
      },
      {
          "deptId":"wbalone100000018d9b",
          "deptName":"测试部01",
          "psnNum":1,
          "psndocList":null,
          "principal":"wbalone100000018d92",
          "principalName":"zy_yg_00",
          "principalAvatar":""
      },
      {
          "deptId":"wbalone100000018d96",
          "deptName":"北分部门测试",
          "psnNum":1,
          "psndocList":null,
          "principal":null,
          "principalName":null,
          "principalAvatar":null
      },
      {
          "deptId":"wbalone100000018d83",
          "deptName":"华刚测试二部",
          "psnNum":5,
          "psndocList":null,
          "principal":null,
          "principalName":null,
          "principalAvatar":null
      },
      {
          "deptId":"wbalone100000018d82",
          "deptName":"华刚测试一部",
          "psnNum":4,
          "psndocList":null,
          "principal":null,
          "principalName":null,
          "principalAvatar":null
      }
    ],
    "psndoc": [{
      "metaDefinedName": "psndoc",
      "namespace": "ifbp",
      "status": 0,
      "changedPropertyNames": null,
      "beanMap": {},
      "id": "wbalone100000018d97",
      "pk_org": "wbalone100000018d95",
      "code": "test001",
      "name": "王海微",
      "usedname": null,
      "birthdate": null,
      "sex": "1",
      "idtype": "0",
      "id_num": "142225200102011013",
      "mnecode": null,
      "joinworkdate": null,
      "addr": null,
      "officephone": "",
      "homephone": "",
      "mobile": "13811089331",
      "email": "wanghai@163.com",
      "def1": null,
      "def2": null,
      "def3": null,
      "def4": null,
      "def5": null,
      "def6": null,
      "def7": null,
      "def8": null,
      "def9": null,
      "def10": null,
      "def11": null,
      "def12": null,
      "def13": null,
      "def14": null,
      "def15": null,
      "def16": null,
      "def17": null,
      "def18": null,
      "def19": null,
      "def20": null,
      "creator": "U001",
      "creationtime": "2018-05-21 11:54:30",
      "modifier": "U001",
      "modifiedtime": "2018-05-21 17:38:57",
      "enablestate": "2",
      "pk_group": null,
      "lastname": null,
      "firstname": null,
      "nickname": null,
      "avatar": "g1/M00/00/03/CgoFQFsCQzGAMB94AADeC-PvieY140.jpg",
      "pk_dept": "wbalone100000018d96",
      "remark": "",
      "issaler": "",
      "dr": 0,
      "ts": 1526973536000,
      "psnjobs": null,
      "id_psnbank": null
    }]
  };
  var userInfo = {
    "psndoc": {
      "metaDefinedName": "psndoc",
      "namespace": "ifbp",
      "status": 0,
      "changedPropertyNames": null,
      "beanMap": {},
      "id": "wbalone100000018d84",
      "pk_org": "wbalone100000018d81",
      "code": "huhg_yg_001",
      "name": "胡华刚1",
      "usedname": null,
      "birthdate": 1526609496000,
      "sex": "1",
      "idtype": "0",
      "id_num": "452722197507190776",
      "mnecode": null,
      "joinworkdate": null,
      "addr": null,
      "officephone": "",
      "homephone": "",
      "mobile": "15100000001",
      "email": "huhuagang@yonyou.com",
      "def1": null,
      "def2": null,
      "def3": null,
      "def4": null,
      "def5": null,
      "def6": null,
      "def7": null,
      "def8": null,
      "def9": null,
      "def10": null,
      "def11": null,
      "def12": null,
      "def13": null,
      "def14": null,
      "def15": null,
      "def16": null,
      "def17": null,
      "def18": null,
      "def19": null,
      "def20": null,
      "creator": "U001",
      "creationtime": "2018-05-18 10:12:59",
      "modifier": "U001",
      "modifiedtime": "2018-05-18 10:12:59",
      "enablestate": "2",
      "pk_group": null,
      "lastname": null,
      "firstname": null,
      "nickname": null,
      "avatar": "",
      "pk_dept": "wbalone100000018d82",
      "remark": "",
      "issaler": "",
      "dr": 0,
      "ts": 1526609580000,
      "psnjobs": null,
      "id_psnbank": null
    },
    "subordinate": 0,
    "bossName": null,
    "bossId": null,
    "pnsjob": {
      "metaDefinedName": "psnjob",
      "namespace": "ifbp",
      "status": 0,
      "changedPropertyNames": null,
      "beanMap": {},
      "pk_psndoc": "wbalone100000018d84",
      "id": "wbalone100000018d85",
      "pk_group": null,
      "pk_org": "wbalone100000018d81",
      "psncode": null,
      "pk_psncl": null,
      "pk_dept": "wbalone100000018d82",
      "ismainjob": "主职",
      "indutydate": 1526572800000,
      "enddutydate": null,
      "jobname": "",
      "def1": "",
      "def2": "",
      "def3": null,
      "def4": null,
      "def5": null,
      "def6": null,
      "def7": null,
      "def8": null,
      "def9": null,
      "def10": null,
      "def11": null,
      "def12": null,
      "def13": null,
      "def14": null,
      "def15": null,
      "def16": null,
      "def17": null,
      "def18": null,
      "def19": null,
      "def20": null,
      "showorder": null,
      "creator": "U001",
      "creationtime": "2018-05-18 10:12:59",
      "modifier": null,
      "modifiedtime": null,
      "job_level": "",
      "job_station": "",
      "contract_number": "",
      "certificate_num": "",
      "certificate_time": null,
      "practice_cert_num": "",
      "dr": 0,
      "ts": 1526609579000
    },
    "corpName": "华刚测试公司",
    "deptName": "华刚测试一部",
    "corpId": "wbalone100000018d81",
    "deptId": "wbalone100000018d82"
  };
  var departmentInfo = {
    "deptId": "wbalone100000018d9b",
    "deptName": "测试部01",
    "psnNum": 1,
    "psndocList": [
      {
        "metaDefinedName": "psndoc",
        "namespace": "ifbp",
        "status": 0,
        "changedPropertyNames": null,
        "beanMap": {},
        "id": "wbalone100000018d92",
        "pk_org": "wbalone100000018d9a",
        "code": "zy_yg_00",
        "name": "zy_yg_00",
        "usedname": null,
        "birthdate": null,
        "sex": null,
        "idtype": "0",
        "id_num": "110222199901110029",
        "mnecode": null,
        "joinworkdate": null,
        "addr": null,
        "officephone": "",
        "homephone": "",
        "mobile": "18101020000",
        "email": "00@yonyou.com",
        "def1": null,
        "def2": null,
        "def3": null,
        "def4": null,
        "def5": null,
        "def6": null,
        "def7": null,
        "def8": null,
        "def9": null,
        "def10": null,
        "def11": null,
        "def12": null,
        "def13": null,
        "def14": null,
        "def15": null,
        "def16": null,
        "def17": null,
        "def18": null,
        "def19": null,
        "def20": null,
        "creator": null,
        "creationtime": null,
        "modifier": null,
        "modifiedtime": null,
        "enablestate": null,
        "pk_group": null,
        "lastname": null,
        "firstname": null,
        "nickname": null,
        "avatar": "",
        "pk_dept": "wbalone100000018d9b",
        "remark": "",
        "issaler": null,
        "dr": 0,
        "ts": null,
        "psnjobs": null,
        "id_psnbank": null
      }
    ]
  };
  return {
    filterResult: filterResult,
    userInfo: userInfo,
    departmentInfo: departmentInfo
  }
})